name = "the_stars"
version = "1.0.0"

description = "A terminal styling and logging framework based off the Golang Charm Lipgloss framework."
licences = ["Apache-2.0"]
repository = { type = "github", user = "Genekkion", repo = "theStars" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
birl = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
